EddyVerbruggen/Calendar-PhoneGap-Plugin

README.md, src/ios/Calendar.h, src/ios/Calendar.m
=> createEventInteractively for ios

src/android/nl/xservices/plugins/accessor/AbstractCalendarAccessor.java
Fix to detect allDay events on multiple days events
=> Fix to detect allDay events on multiple days events

src/android/nl/xservices/plugins/accessor/AbstractCalendarAccessor.java, src/ios/Calendar.m
DeleteEvent doesn’t work in Android, so I did a fix to resolve this problem;
Allows the title search for "starts with" not just with the exact string (Android and iOS).
=> Delete Event Android and Find Events

src/android/nl/xservices/plugins/Calendar.java, src/android/nl/xservices/plugins/accessor/AbstractCalendarAccessor.java, src/android/nl/xservices/plugins/accessor/CalendarProviderAccessor.java, src/android/nl/xservices/plugins/accessor/LegacyCalendarAccessor.java, www/Calendar.js
I really needed this so I am sharing. Thanks for great plugin!
=> Added support for calendar id on android.

README.md
Please review second sentence since I am not entirely sure of that. This might resolve #159  Thanks :)
=> Fixed docs regarding Android calendarId.

src/ios/Calendar.m
Fixes the issue of being unable to fill the URL Field in a Calendar Event.
=> Add events with URL Field

README.md
I made a table to get an overview of the basic operations supported on each platform. I thought that maybe you are interested to include it in the README usage section.
=> Added a operations compatibility table to README.

src/ios/Calendar.m
Minor fixes, nothing too controversial I hope.
=> Fixes for issue 226, cannot search in event title, and 227 only searches first calendar

src/android/nl/xservices/plugins/Calendar.java
Included recurring events in listEventInRange method (only for Android)
=> Get recurring events on Android

src/android/nl/xservices/plugins/Calendar.java, src/android/nl/xservices/plugins/accessor/AbstractCalendarAccessor.java
i've extended the intent creation to add recurrence for interactively created events on android
=> add recurrence for interactive events

README.md
Hi,
added return examples for
- events ios
- getCalOptions ios
- getCalendars ios 
decide self if you want it or not..
=> added example of returned objects

src/android/nl/xservices/plugins/Calendar.java
check https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/issues/304
=> fixed timezone issue with createinteractively

README.md, plugin.xml
=> Add configurable iOS permission

src/ios/Calendar.m
=> Fix Warning

src/android/nl/xservices/plugins/Calendar.java, src/android/nl/xservices/plugins/accessor/AbstractCalendarAccessor.java, src/android/nl/xservices/plugins/accessor/CalendarProviderAccessor.java, src/android/nl/xservices/plugins/accessor/LegacyCalendarAccessor.java, www/Calendar.js
Parsing recurring entries in the plugin and adding all necessary properties
to the returned event
=> Parsing recurring entries

src/android/nl/xservices/plugins/accessor/AbstractCalendarAccessor.java, src/android/nl/xservices/plugins/accessor/CalendarProviderAccessor.java, src/android/nl/xservices/plugins/accessor/LegacyCalendarAccessor.java
add displayname for listCalendar()
=> add displayname for listCalendar

src/android/nl/xservices/plugins/Calendar.java, src/android/nl/xservices/plugins/accessor/AbstractCalendarAccessor.java
Actual plugin does not work with recurrence events in Android (start->undefined). This pull repair this problem.
It is very easy demostrate that actual does not work.
Now in working with this fork, and at the moment it works fine.
=> Issue in Android with recurrent events

src/android/nl/xservices/plugins/accessor/AbstractCalendarAccessor.java
Fix issue when NullPointerException if exist calendar without name
https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/issues/394
=> Fix NullPointerException if exist calendar without name

src/android/nl/xservices/plugins/Calendar.java, src/android/nl/xservices/plugins/accessor/AbstractCalendarAccessor.java
I check it this simple change and it seems to fix this issue:
https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/issues/473
Regards
=> fixing unreliable index

src/android/nl/xservices/plugins/accessor/AbstractCalendarAccessor.java
Please merge the Primary Calendar change, some Android Calendar have Primary Column name different
=> fixing primary calendar issue

src/android/nl/xservices/plugins/Calendar.java
=> Add check if allday is set if event is created interactively

src/ios/Calendar.m
Check if optional notes and location properties are existent before adding them.
=> Fix possible plugin crash (iOS 13)

src/ios/Calendar.m
In createEventInteractively and createEventWithCalendar
=> Fix iOS 13 crash
